version: '3.3'

services:
  graphql:
    image: graphql
    build: .
    ports:
      - '127.0.0.1:6000:3000'
    # volumes:
    #   - './:/webapp/'
    environment:
      HOST: 0.0.0.0
      PORT: 3000
