version: '3.3'

services:
  rest:
    image: rest
    build: .
    network_mode: 'host'
    # ports:
      # - '127.0.0.1:4000:4000'
      # - '127.0.0.1:7227:7227'
    # volumes:
    #   - './:/webapp/'
    environment:
      HOST: 127.0.0.1
      PORT: 4000
