version: '3.3'

services:
  nexash:
    build: .
    image: nexash
    container_name: nexash
    restart: always
    network_mode: 'host'
    # ports:
    #   - '127.0.0.1:3000:3000'
    # volumes:
    #   - './:/webapp/'
    environment:
      HOST: 0.0.0.0
      PORT: 3000
