version: '3.3'

services:
  nexash:
    image: nexash
    build: .
    ports:
      - '127.0.0.1:3000:3000'
    # volumes:
    #   - './:/webapp/'
    environment:
      HOST: 0.0.0.0
      PORT: 3000
